name: landloc
dependencies:
  - python=3.6.8
  - pip=19.1.1
  - h5py=2.8.0
  - pytorch=1.0.1
  - torchvision=0.2.*
  - cudatoolkit=10.*
  - pyyaml=3.13.*
  - tqdm=4.19.*
  - scipy=1.1.0
  - numpy=1.13.*
  - cython=0.28.5
  - pandas=0.23.*
  - matplotlib=3.1.0
  - seaborn=0.10.1
  - opencv-contrib-python=3.4.2
