name: alexnet


localization:
  planar: False
  cheat: False
  metric: cosine
  ransacThreshold: 6
  subFeatureMetric: euclidean
  # ratioThreshold: 0.15

extractor:
  type: alexnet
  oeKwargs:
    feature: [pool1, conv2, pool2, conv3, conv4, conv5, pool5]
    patchSize: 64
    filterSmall: False
    filterAtEdges: False
    siftSubFeatures: True

    eb_params:
      model_path: '/usr/local/faststorage/ahollid/landmark_localizer/model.yml'
      maxBoxes: 250
      alpha: 0.55
      beta: 0.55
      maxAspectRatio: 6
