name: densenet_all

localization:
  planar: False
  cheat: False
  metric: cosine
  ransacThreshold: 6
  subFeatureMetric: euclidean
  # ratioThreshold: 0.15

extractor:
  type: [densenet121, densenet169, densenet201]
  oeKwargs:
    feature: [denseblock1, transition1, denseblock2, transition2, denseblock3, transition3, denseblock4]
    patchSize: 64
    filterSmall: False
    filterAtEdges: False
    siftSubFeatures: True
    eb_params:
      model_path: '/usr/local/faststorage/ahollid/landmark_localizer/model.yml'
      maxBoxes: 250
      alpha: 0.55
      beta: 0.55
      maxAspectRatio: 6
