name: resnet_redux
localization:
  planar: False
  cheat: False
  metric: cosine
  ransacThreshold: 6
  subFeatureMetric: euclidean

extractor:
  type: [resnet50, resnet101, resnet152]
  oeKwargs:
    feature: [res4f, res5c]
    patchSize: 64
    filterSmall: False
    filterAtEdges: False
    siftSubFeatures: True

    eb_params:
      model_path: 'model.yml'
      maxBoxes: 500
      alpha: 0.55
      beta: 0.55
      maxAspectRatio: 6
