name: vgg_all
localization:
  planar: False
  cheat: False
  metric: cosine
  ransacThreshold: 6
  subFeatureMetric: euclidean

extractor:
  type: [vgg11, vgg13, vgg16, vgg19]
  oeKwargs:
    feature: [pool2, pre_pool3, pool3, pre_pool4, pool4, pre_pool5, pool5]
    patchSize: 64
    filterSmall: False
    filterAtEdges: False
    siftSubFeatures: True

    eb_params:
      model_path: '/home/a.holliday/landmark_localizer/model.yml'
      maxBoxes: 500
      alpha: 0.55
      beta: 0.55
      maxAspectRatio: 6
